# Site settings
title: MatrixWood
email: wwc7033@gmail.com
author: CanftIn
description: A blog by CanftIn
baseurl: ""
url: "https://CanftIn.com"
favicon: /favicon.png
twitter: CanftIn
github_username: CanftIn
permalink: /:year/:month-:day-:title.html
domain: CanftIn.com
# Build settings
markdown: kramdown
toc_levels: 1..2
exclude:
  - '*.lagda.md'
  - '*.agdai'
  - '.idea'
  - '.vscode'
  - '_posts/_build'
highlighter: rouge
repository_name: CanftIn.github.io