baseURL = 'https://canftin.github.io/'
languageCode = 'zh-cn'
title = "CanftIn's Blog"
theme = "PaperMod"

enableInlineShortcodes = true #允许内联短码
enableEmoji = true            # 允许使用 Emoji 表情，建议 true
enableRobotsTXT = true        # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage = true         # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

#googleAnalytics: UA-123-45 # 谷歌统计
#Copyright = """Copyright © 2016-2023 CanftIn, 许可协议：<a class=link href=https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh target=_blank rel=noopener>CC BY-NC-ND 4.0</a>, """

buildDrafts = false
buildFuture = false
buildExpired = false

paginate = 15 # 每页显示的文章数
# defaultContentLanguage = "zh"         # 最顶部首先展示的语言页面
# defaultContentLanguageInSubdir = true

[minify]
disableXML = true
# minifyOutput = true

# 浏览器链接显示方式
[permalinks]
post = "/:title/"

[languages.en]
languageName = "English"
#contentDir = "content/en"
weight = 1

[languages.en.profileMode]
enabled = true
title = "矩木的博客"
subtitle = "有一只叫布丁的猫 ᗢᕡᓗ <br/>"
imageUrl = "img/buding.jpeg"
imageWidth = 250
imageHeight = 250

[[languages.en.profileMode.buttons]]
name = "技术"
url = "posts/tech"

[[languages.en.profileMode.buttons]]
name = "阅读"
url = "posts/read"

[[languages.en.profileMode.buttons]]
name = "生活"
url = "posts/life"

[[languages.en.menu.main]]
identifier = "search"
name = "搜索"
url = "search"
weight = 1

[[languages.en.menu.main]]
identifier = "home"
name = "主页"
url = "/"
weight = 2

[[languages.en.menu.main]]
identifier = "posts"
name = "文章"
url = "posts"
weight = 3

[[languages.en.menu.main]]
identifier = "archives"
name = "归档"
url = "archives/"
weight = 20

[[languages.en.menu.main]]
identifier = "tags"
name = "标签"
url = "tags"
weight = 40

[[languages.en.menu.main]]
identifier = "about"
name = "关于"
url = "about"
weight = 50

# [[languages.en.menu.main]]
# identifier = "links"
# name = "友链"
# url = "links"
# weight = 60

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
author = "CanftIn"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true         # 显示文章更新时间
ShowToc = true             # 显示目录
TocOpen = true             # 自动展开目录
comments = true
StartYear = 2016

[[params.socialIcons]]
name = "github"
url = "https://github.com/CanftIn"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/canftin_"

# [[params.socialIcons]]
# name = "facebook"
# url = ""
# 
# [[params.socialIcons]]
# name = "instagram"
# url = ""
# 
# [[params.socialIcons]]
# name = "QQ"
# url = ""

[[params.socialIcons]]
name = "WeChat"
url = "https://github.com/CanftIn/CanftIn"

[[params.socialIcons]]
name = "email"
url = "wwc7033@gmail.com"

[[params.socialIcons]]
name = "RSS"
url = "index.xml"

[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax

[params.label]
text = "CanftIn's Blog"
#icon = "img/text_icon.ico"
#iconHeight = 30

[params.assets]
favicon = "img/text_icon.ico"
favicon16x16 = "img/text_icon.ico"
favicon32x32 = "img/text_icon.ico"
apple_touch_icon = "text_icon.ico"
safari_pinned_tab = "text_icon.ico"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 1
minMatchCharLength = 0
keys = ["title", "permalink", "summary"]

[params.twikoo]
version = "1.4.11"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true # enable html in markdown

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
style = "monokai" # syntax highlight style, see https://xyproto.github.io/splash/docs/

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
